# Generated by Django 5.0.14 on 2026-10-08 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('most_purchased_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='most_purchased_statistics', to='movies.movie')),
                ('most_reviewed_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='most_reviewed_statistics', to='movies.movie')),
            ],
        ),
    ]
