# Generated by Django 5.0.14 on 2026-10-08 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_statistics'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Statistics',
            new_name='Statistic',
        ),
    ]
