# Generated by Django 5.0.14 on 2026-10-08 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_rename_statistics_statistic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='most_purchased_movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='most_purchased_statistics', to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='most_reviewed_movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='most_reviewed_statistics', to='movies.movie'),
        ),
    ]
