# Generated by Django 5.0 on 2026-10-07 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_remove_rating_unique_movie_user_rating_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rating',
            name='unique_movie_user_rating',
        ),
    ]
