# Generated by Django 5.0 on 2026-10-09 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_statistic_most_purchased_movie_and_more'),
        ('movies', '0007_rating_unique_rating_per_user_per_movie'),
    ]

    operations = [
    ]
